# Generated by Django 3.2.12 on 2022-07-25 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attributenames',
            fields=[
                ('attributeid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=110)),
            ],
            options={
                'db_table': 'attributenames',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryid', models.IntegerField(primary_key=True, serialize=False)),
                ('isactive', models.BooleanField()),
                ('ordernumber', models.IntegerField()),
                ('catlevel', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categorydisplayattributes',
            fields=[
                ('cat_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isactive', models.BooleanField()),
                ('templatetype', models.IntegerField()),
                ('displayorder', models.IntegerField()),
            ],
            options={
                'db_table': 'categorydisplayattributes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoryheader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isactive', models.BooleanField()),
                ('templatetype', models.IntegerField()),
                ('displayorder', models.IntegerField()),
            ],
            options={
                'db_table': 'categoryheader',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categorysearchattributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isactive', models.BooleanField()),
            ],
            options={
                'db_table': 'categorysearchattributes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Headernames',
            fields=[
                ('headerid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'headernames',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Locales',
            fields=[
                ('localeid', models.IntegerField(primary_key=True, serialize=False)),
                ('isactive', models.BooleanField()),
                ('languagecode', models.CharField(max_length=5)),
                ('countrycode', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'locales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('manufacturerid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('logowidth', models.IntegerField()),
                ('logoheight', models.IntegerField()),
            ],
            options={
                'db_table': 'manufacturer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Manufacturermapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturername', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'manufacturermapping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.IntegerField(primary_key=True, serialize=False)),
                ('isactive', models.BooleanField()),
                ('mfgpartno', models.CharField(max_length=70)),
                ('isaccessory', models.BooleanField(default=False)),
                ('equivalency', models.FloatField()),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('modifieddate', models.DateTimeField(auto_now_add=True)),
                ('lastupdated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productaccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isactive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'productaccessories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productattribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setnumber', models.SmallIntegerField()),
                ('displayvalue', models.TextField(blank=True, null=True)),
                ('absolutevalue', models.FloatField()),
                ('isabsolute', models.BooleanField()),
                ('isactive', models.BooleanField()),
                ('type', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'productattribute',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productdescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('isdefault', models.BooleanField()),
                ('type', models.IntegerField()),
                ('isactive', models.BooleanField()),
            ],
            options={
                'db_table': 'productdescriptions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productelementproperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertykey', models.CharField(max_length=60)),
                ('propertyvalue', models.CharField(max_length=250)),
                ('isactive', models.BooleanField()),
            ],
            options={
                'db_table': 'productelementproperties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productelements',
            fields=[
                ('productelementid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=60)),
                ('status', models.CharField(max_length=60)),
                ('isactive', models.BooleanField()),
            ],
            options={
                'db_table': 'productelements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productfeatures',
            fields=[
                ('productfeatureid', models.DecimalField(decimal_places=0, max_digits=24, primary_key=True, serialize=False)),
                ('ordernumber', models.SmallIntegerField()),
                ('text', models.CharField(max_length=1000)),
                ('modifieddate', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.BooleanField()),
            ],
            options={
                'db_table': 'productfeatures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productkeywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=900)),
                ('isactive', models.BooleanField()),
            ],
            options={
                'db_table': 'productkeywords',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productlocales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isactive', models.BooleanField()),
                ('status', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'productlocales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productsimilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isactive', models.BooleanField()),
            ],
            options={
                'db_table': 'productsimilar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productskus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('sku', models.CharField(max_length=60)),
                ('addeddate', models.DateTimeField(blank=True, null=True)),
                ('isactive', models.BooleanField()),
            ],
            options={
                'db_table': 'productskus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productupsell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isactive', models.BooleanField()),
            ],
            options={
                'db_table': 'productupsell',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SearchAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setnumber', models.SmallIntegerField()),
                ('isactive', models.BooleanField()),
            ],
            options={
                'db_table': 'search_attribute',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SearchAttributeValues',
            fields=[
                ('valueid', models.IntegerField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('absolutevalue', models.FloatField()),
                ('isabsolute', models.BooleanField()),
            ],
            options={
                'db_table': 'search_attribute_values',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, max_length='max', null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unitnames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'unitnames',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('unitid', models.IntegerField(primary_key=True, serialize=False)),
                ('baseunitid', models.IntegerField()),
                ('multiple', models.FloatField()),
            ],
            options={
                'db_table': 'units',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categorynames',
            fields=[
                ('categoryid', models.OneToOneField(db_column='categoryid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='categorylol', serialize=False, to='core.category')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'categorynames',
                'managed': False,
            },
        ),
    ]
