from core.admin import attributename_admin
from core.admin import category_admin
from core.admin import categorydisplayattribute_admin
from core.admin import categoryheader_admin
from core.admin import categoryname_admin
from core.admin import categorysearchattribute_model
from core.admin import headername_admin
from core.admin import locale_admin
from core.admin import manufacturer_admin
from core.admin import manufacturermapping_admin
from core.admin import product_admin
from core.admin import productaccessory_admin
from core.admin import productattribute_admin
from core.admin import productdescription_admin
from core.admin import productelement_admin
from core.admin import productelementproperty_admin
from core.admin import productfeacture_admin
from core.admin import productkeyword_admin
from core.admin import productlocal_admin
from core.admin import productsimilar_admin
from core.admin import productsku
from core.admin import productupsell_admin
from core.admin import searchattribute_admin
from core.admin import searchattributevalue_admin
from core.admin import sysdiagram_admin
from core.admin import unit_admin
from core.admin import unitname_admin
